# Generated by Django 4.2.27 on 2026-02-11 19:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('generation', models.PositiveSmallIntegerField(help_text='기수 (예: 13)')),
                ('description', models.TextField(blank=True, help_text='한 줄소개')),
                ('detail', models.TextField(blank=True, help_text='서비스 상세 설명')),
                ('tech_stack', models.CharField(blank=True, help_text='쉼표 구분 기술 스택', max_length=500)),
                ('github_url', models.URLField(blank=True)),
                ('team_members', models.CharField(blank=True, help_text='쉼표 구분 팀원', max_length=500)),
                ('thumbnail', models.ImageField(upload_to='projects/thumbnails/')),
                ('pdf_file', models.FileField(upload_to='projects/pdfs/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
