# Generated by Django 4.2.27 on 2026-03-31 23:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import sessionsapp.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sessionsapp', '0005_classreview_delete_studentreview'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeworkCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track', models.CharField(choices=[('FULLSTACK', '풀스택')], default='FULLSTACK', max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('week', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homework_categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['week', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HomeworkSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_file', models.FileField(upload_to=sessionsapp.models.homework_pdf_upload_path)),
                ('submitted_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='sessionsapp.homeworkcategory')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homework_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
                'unique_together': {('category', 'student')},
            },
        ),
    ]
