# Generated by Django 4.2.27 on 2026-02-02 04:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationdraft',
            name='user',
        ),
        migrations.AddField(
            model_name='application',
            name='experience',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='application',
            name='motivation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='application',
            name='one_liner',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='application',
            name='portfolio_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='application',
            name='track',
            field=models.CharField(choices=[('PLANNING_DESIGN', '기획/디자인'), ('FULLSTACK', '풀스택'), ('AI_SERVER', 'AI/서버')], default='FULLSTACK', max_length=30),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('DRAFT', '임시저장'), ('SUBMITTED', '제출완료'), ('ACCEPTED', '합격'), ('REJECTED', '불합격')], default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='application',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('user',)},
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['status'], name='application_status_1508e0_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['track'], name='application_track_61dc41_idx'),
        ),
        migrations.DeleteModel(
            name='ApplicationDraft',
        ),
        migrations.RemoveField(
            model_name='application',
            name='data',
        ),
    ]
