# Generated by Django 4.2.27 on 2026-02-02 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_remove_applicationdraft_user_application_experience_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='track',
            field=models.CharField(choices=[('PLANNING_DESIGN', '기획/디자인'), ('FRONTEND', '프론트엔드'), ('BACKEND', '백엔드'), ('AI_SERVER', 'AI/서버')], default='PLANNING_DESIGN', max_length=30),
        ),
    ]
