# Generated by Django 4.2.27 on 2026-02-02 09:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('applications', '0004_migrate_fullstack_track'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('DOC', '서류'), ('INTERVIEW', '면접')], max_length=20)),
                ('score1', models.PositiveSmallIntegerField(default=0)),
                ('score2', models.PositiveSmallIntegerField(default=0)),
                ('score3', models.PositiveSmallIntegerField(default=0)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='applications.application')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_scores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['kind'], name='application_kind_87c44f_idx'), models.Index(fields=['application', 'kind'], name='application_applica_cb78ba_idx')],
                'unique_together': {('application', 'reviewer', 'kind')},
            },
        ),
    ]
