# Generated by Django 4.2.27 on 2026-02-04 10:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('applications', '0005_applicationscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='final_decision',
            field=models.CharField(choices=[('PENDING', '미확정'), ('ACCEPTED', '최종합격'), ('REJECTED', '최종불합격')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='application',
            name='finalized_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='finalized_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finalized_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['final_decision'], name='application_final_d_488657_idx'),
        ),
    ]
