# Generated by Django 4.2.27 on 2026-02-04 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0006_application_final_decision_application_finalized_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='finalized_by',
        ),
        migrations.AddField(
            model_name='application',
            name='doc_decision',
            field=models.CharField(choices=[('PENDING', '미확정'), ('ACCEPTED', '합격 확정'), ('REJECTED', '불합격 확정')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='application',
            name='doc_finalized_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='final_decision',
            field=models.CharField(choices=[('PENDING', '미확정'), ('ACCEPTED', '합격 확정'), ('REJECTED', '불합격 확정')], default='PENDING', max_length=20),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['doc_decision'], name='application_doc_dec_c9ecb9_idx'),
        ),
    ]
