# Generated by Django 4.2.27 on 2026-02-11 00:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('applications', '0007_remove_application_finalized_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultNotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview_location', models.CharField(default='향설생활관 1관 RC218', max_length=200, verbose_name='면접 장소')),
                ('interview_date', models.CharField(default='2026년 03월 05일', max_length=100, verbose_name='면접 일자')),
                ('interview_deadline', models.CharField(default='18:00 까지', max_length=100, verbose_name='입실 시간')),
                ('ot_datetime', models.CharField(default='2026년 03월 09일 18:00', max_length=100, verbose_name='OT 일시')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_updates', to=settings.AUTH_USER_MODEL, verbose_name='수정자')),
            ],
            options={
                'verbose_name': '합격 알림 설정',
                'verbose_name_plural': '합격 알림 설정',
            },
        ),
    ]
