# Generated by Django 4.2.27 on 2026-02-11 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0008_resultnotificationsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='ai_programming_level',
            field=models.TextField(blank=True, verbose_name='프로그래밍 학습 경험'),
        ),
        migrations.AddField(
            model_name='application',
            name='ai_service_impression',
            field=models.TextField(blank=True, verbose_name='AI 서비스 인상'),
        ),
        migrations.AddField(
            model_name='application',
            name='backend_code_quality',
            field=models.TextField(blank=True, verbose_name='코드 품질 기준'),
        ),
        migrations.AddField(
            model_name='application',
            name='backend_web_process',
            field=models.TextField(blank=True, verbose_name='웹 동작 원리'),
        ),
        migrations.AddField(
            model_name='application',
            name='common_growth_experience',
            field=models.TextField(blank=True, verbose_name='열정적으로 몽입했던 경험'),
        ),
        migrations.AddField(
            model_name='application',
            name='common_teamwork',
            field=models.TextField(blank=True, verbose_name='팀 협업 경험'),
        ),
        migrations.AddField(
            model_name='application',
            name='common_time_management',
            field=models.TextField(blank=True, verbose_name='시간 관리 계획'),
        ),
        migrations.AddField(
            model_name='application',
            name='frontend_design_implementation',
            field=models.TextField(blank=True, verbose_name='디자인 구현 우선순위'),
        ),
        migrations.AddField(
            model_name='application',
            name='frontend_ui_experience',
            field=models.TextField(blank=True, verbose_name='UI/UX 개선 아이디어'),
        ),
        migrations.AddField(
            model_name='application',
            name='planning_experience',
            field=models.TextField(blank=True, verbose_name='기획/디자인 경험'),
        ),
        migrations.AddField(
            model_name='application',
            name='planning_idea',
            field=models.TextField(blank=True, verbose_name='사회 문제 해결 아이디어'),
        ),
        migrations.AlterField(
            model_name='application',
            name='experience',
            field=models.TextField(blank=True, verbose_name='기타 경험'),
        ),
        migrations.AlterField(
            model_name='application',
            name='motivation',
            field=models.TextField(blank=True, verbose_name='자기소개 및 지원동기'),
        ),
    ]
