# Generated by Django 4.2.27 on 2026-02-23 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0010_alter_application_track'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='personal_interview_datetime',
            field=models.CharField(blank=True, max_length=100, verbose_name='개별 면접 일시'),
        ),
        migrations.AddField(
            model_name='application',
            name='personal_interview_location',
            field=models.CharField(blank=True, max_length=200, verbose_name='개별 면접 장소'),
        ),
    ]
