# Generated by Django 4.2.27 on 2026-02-02 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_emailverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverification',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
